#!/usr/bin/env python3
import json
import os
import re
import sys
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse

HOST = "127.0.0.1"
PORT = 8789
BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DESIGN_DIR = os.path.join(BASE, "data", "designs")

os.makedirs(DESIGN_DIR, exist_ok=True)

def safe_name(text):
    text = re.sub(r"[^a-zA-Z0-9_-]+", "-", text.lower()).strip("-")
    return text[:50] or "design"

def make_svg(prompt):
    title = (
        prompt.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    return f'''<svg xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 1200 720">
<rect width="1200" height="720" fill="#05070b"/>
<rect width="240" height="720" fill="#0a0f18"/>
<rect x="240" width="960" height="72" fill="#0d1420"/>

<text x="32" y="48"
fill="#ffffff"
font-size="25"
font-family="Arial"
font-weight="bold">CLRICKS</text>

<text x="275" y="45"
fill="#ffffff"
font-size="21"
font-family="Arial">{title}</text>

<rect x="270" y="110"
width="270" height="130"
rx="12"
fill="#111a27"/>

<rect x="565" y="110"
width="270" height="130"
rx="12"
fill="#111a27"/>

<rect x="860" y="110"
width="270" height="130"
rx="12"
fill="#111a27"/>

<rect x="270" y="275"
width="560" height="330"
rx="12"
fill="#0d1420"/>

<rect x="855" y="275"
width="275" height="330"
rx="12"
fill="#0d1420"/>

<text x="290" y="150"
fill="#8ea0b8"
font-size="15"
font-family="Arial">PROJECT</text>

<text x="290" y="195"
fill="#ffffff"
font-size="31"
font-family="Arial">ONLINE</text>

<text x="585" y="150"
fill="#8ea0b8"
font-size="15"
font-family="Arial">AGENT TASKS</text>

<text x="585" y="195"
fill="#ffffff"
font-size="31"
font-family="Arial">READY</text>

<text x="880" y="150"
fill="#8ea0b8"
font-size="15"
font-family="Arial">BUILD</text>

<text x="880" y="195"
fill="#ffffff"
font-size="31"
font-family="Arial">READY</text>

<text x="290" y="315"
fill="#ffffff"
font-size="20"
font-family="Arial">AGENT WORKSPACE</text>

<text x="290" y="355"
fill="#718096"
font-size="15"
font-family="monospace">$ agent task build project</text>

<text x="290" y="385"
fill="#718096"
font-size="15"
font-family="monospace">$ git status</text>

<text x="290" y="415"
fill="#718096"
font-size="15"
font-family="monospace">$ review latest changes</text>

<text x="875" y="315"
fill="#ffffff"
font-size="20"
font-family="Arial">ACTIVITY</text>

<text x="875" y="355"
fill="#718096"
font-size="14"
font-family="Arial">Agent connected</text>

<text x="875" y="385"
fill="#718096"
font-size="14"
font-family="Arial">Design generated</text>

<text x="875" y="415"
fill="#718096"
font-size="14"
font-family="Arial">Preview ready</text>
</svg>'''

def make_html(prompt):
    title = (
        prompt.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    return f'''<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
*{{box-sizing:border-box}}
body{{
margin:0;
background:#05070b;
color:white;
font-family:Arial,sans-serif
}}
.app{{
min-height:100vh;
display:grid;
grid-template-columns:230px 1fr
}}
aside{{
background:#0a0f18;
padding:25px
}}
.logo{{
font-size:25px;
font-weight:bold;
margin-bottom:40px
}}
nav{{
display:grid;
gap:18px;
color:#8ea0b8
}}
main{{
padding:28px
}}
.grid{{
display:grid;
grid-template-columns:repeat(3,1fr);
gap:16px
}}
.card{{
background:#0d1420;
border:1px solid #182334;
border-radius:12px;
padding:22px
}}
.value{{
font-size:32px;
font-weight:bold;
margin-top:10px
}}
.workspace{{
margin-top:16px;
min-height:300px
}}
.muted{{
color:#718096
}}
@media(max-width:750px){{
.app{{grid-template-columns:1fr}}
aside{{display:none}}
.grid{{grid-template-columns:1fr}}
main{{padding:18px}}
}}
</style>
</head>
<body>

<div class="app">

<aside>
<div class="logo">CLRICKS</div>
<nav>
<div>Agent IDE</div>
<div>Terminal</div>
<div>Projects</div>
<div>Packages</div>
<div>Settings</div>
</nav>
</aside>

<main>

<h1>{title}</h1>

<div class="grid">

<div class="card">
<div class="muted">PROJECT</div>
<div class="value">ONLINE</div>
</div>

<div class="card">
<div class="muted">AGENT</div>
<div class="value">READY</div>
</div>

<div class="card">
<div class="muted">BUILD</div>
<div class="value">READY</div>
</div>

</div>

<div class="card workspace">
<h2>Agent Workspace</h2>
<p class="muted">
Generated by Clriks Python Design Engine.
</p>
</div>

</main>
</div>

</body>
</html>'''

class Handler(BaseHTTPRequestHandler):

    def json_response(self, status, data):
        body = json.dumps(
            data,
            ensure_ascii=False
        ).encode()

        self.send_response(status)
        self.send_header(
            "Content-Type",
            "application/json; charset=utf-8"
        )
        self.send_header(
            "Content-Length",
            str(len(body))
        )
        self.send_header(
            "Access-Control-Allow-Origin",
            "*"
        )
        self.end_headers()

        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header(
            "Access-Control-Allow-Origin",
            "*"
        )
        self.send_header(
            "Access-Control-Allow-Headers",
            "Content-Type"
        )
        self.send_header(
            "Access-Control-Allow-Methods",
            "GET,POST,OPTIONS"
        )
        self.end_headers()

    def do_GET(self):
        path = urlparse(self.path).path

        if path == "/health":
            self.json_response(200, {
                "ok": True,
                "service": "clriks-python-design-engine",
                "python": sys.version.split()[0],
                "port": PORT
            })
            return

        self.json_response(
            404,
            {"ok": False, "error": "not_found"}
        )

    def do_POST(self):
        path = urlparse(self.path).path

        if path != "/design/generate":
            self.json_response(
                404,
                {"ok": False, "error": "not_found"}
            )
            return

        try:
            length = int(
                self.headers.get(
                    "Content-Length",
                    "0"
                )
            )

            raw = self.rfile.read(length)

            data = json.loads(
                raw.decode("utf-8")
            )

            prompt = str(
                data.get("prompt", "")
            ).strip()

            fmt = str(
                data.get("format", "svg")
            ).lower()

            if not prompt:
                raise ValueError(
                    "prompt is required"
                )

            if fmt not in ("svg", "html"):
                raise ValueError(
                    "format must be svg or html"
                )

            design_id = uuid.uuid4().hex[:12]
            name = safe_name(prompt)

            if fmt == "svg":
                content = make_svg(prompt)
                filename = (
                    f"{design_id}-{name}.svg"
                )
            else:
                content = make_html(prompt)
                filename = (
                    f"{design_id}-{name}.html"
                )

            path = os.path.join(
                DESIGN_DIR,
                filename
            )

            with open(
                path,
                "w",
                encoding="utf-8"
            ) as f:
                f.write(content)

            self.json_response(200, {
                "ok": True,
                "id": design_id,
                "format": fmt,
                "file": path,
                "url": f"/designs/{filename}"
            })

        except Exception as e:
            self.json_response(400, {
                "ok": False,
                "error": str(e)
            })

    def log_message(self, fmt, *args):
        print("[CLRICKS-PY]", fmt % args)

def main():
    print(
        f"CLRICKS PYTHON DESIGN ENGINE"
    )
    print(
        f"LISTENING http://{HOST}:{PORT}"
    )

    server = ThreadingHTTPServer(
        (HOST, PORT),
        Handler
    )

    server.serve_forever()

if __name__ == "__main__":
    main()
